### ISSUE TITLE
Dark Ethereal Glass is opaque

### ISSUE THREAD

**Issue by Shyclops** [Lykrast/Glassential#14]
Dark Ethereal Glass is opaque
![image](https://user-images.githubusercontent.com/10409204/150661368-741880e1-9947-4cd6-8d11-4704b8d103a0.png)

**Comment by Lykrast** [comment]
There's a lot of missing info:

* What version of the mod do you have?
* What version of Forge are you on?
* What are all the other mods in your instance/pack?
* Do you have a shader mod like Optifine in there?

**Comment by Shyclops** [comment]
hi sorry
mod version: glassential-forge-1.18-1.2.1.jar
forge version: 39.0.43
other mods: All the mods 7 - version 0.2.34 (https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/relations/dependencies)
no shaders, just straight all the mods 7

**Comment by Lykrast** [comment]
The good news is that this doesn't happen on a fresh forge instance with just glassential, so it's definitely some weird mod interaction. That makes it harder to track though so that may take a while to find who's the culprit.

**Comment by Shyclops** [comment]
aah 
thanks, i'll keep testing different things on my end too

**Comment by DreamingLamb** [comment]
Been having the same issue with a custom modpack, so thought I'd have a look...

Clean install of Forge 1.18.1 39.0.64 and Glassentials 1.18 1.2.1
![image](https://user-images.githubusercontent.com/14001645/153569479-f1c020a2-3477-4387-bfee-d057d8fc306f.png)

Added CTM 1.18-1.1.3+1
![image](https://user-images.githubusercontent.com/14001645/153570777-a3d728c1-b54b-41a6-ace3-e4ad28283c97.png)


So took CTM out of the larger modpack I'm using and it's 'fixed'.
![image](https://user-images.githubusercontent.com/14001645/153570318-c5041351-80ef-4394-8ff7-0b9e9983f19d.png)

**Comment by Lykrast** [comment]
Thanks for the detailled breakdown, I'll see what I can do.

**Comment by DreamingLamb** [comment]
All good.  Did have a look at what I can, ctm texture seems fine, has transprency.  The mcmeta seems to match what CTM uses, so unless they've made a change and not announced it (not checked the github) or something in your code is different for ctm's, I can't see a reason.

**Comment by DreamingLamb** [comment]
Thanks for sorting so quick!  Updated and it's working with both a clean pack and the larger one :)
![image](https://user-images.githubusercontent.com/14001645/153595037-9e5147a6-4ac0-4638-84e3-d5e1a2eb9ae1.png)
