### ISSUE TITLE
ATM7 Client Crashes

### ISSUE THREAD

**Issue by TristonWasik** [Lykrast/Glassential#16]
![image](https://user-images.githubusercontent.com/32952542/177413775-e4d8c34f-2ee8-4c99-b961-3053f20991b6.png)

I'm getting the above error on clientside when loading into the world. I've attached the full crash log.

[crash-2022-07-05_12.47.07-client.txt](https://github.com/Lykrast/Glassential/files/9049613/crash-2022-07-05_12.47.07-client.txt)

**Comment by Lykrast** [comment]
That issue is on CTM's side sadly. It's reported there https://github.com/Chisel-Team/ConnectedTexturesMod/issues/174 so there isn't anything I can do about it.

In the mean time you can try removing CTM from your installation.
