### ISSUE TITLE
[1.16.5] Connected glass textures having a mind of their own

### ISSUE THREAD

**Issue by SnakerBone** [Lykrast/Glassential#17]
Hey so the connected glass is refusing to connect. Everytime there's a small block update that happens near the glass, they either connect or unconnect, the order they connect/unconnect seems entirely random. I cant really understand what would be causing this. Thought I'd report this issue

[javaw_CFwqhCXfLB.webm](https://user-images.githubusercontent.com/55041473/208392494-c90c79bb-b66d-4e13-a4ff-d2beb3a66ae6.webm)

**Comment by Lykrast** [comment]
No idea either,most likely an issue with CTM since that's what's handling connectected textures. Try updating that.

Either way there's no logic for connecting textures in this mod so don't think it can be on this side.
