### ISSUE TITLE
[Fabric 1.20.1] - Version 2.0.0 - Some glass disappear after touching water

### ISSUE THREAD

**Issue by DoriTran** [Lykrast/Glassential#19]
Some walk throughable glass block from your mod like ghost glass is disapear right after touching water
I have test it with fabric api version 0.89.0, no other mod is install.
Can you check this bug and release a fix on Fabric 1.20.1, thanks ♥

**Comment by Lykrast** [comment]
Wrong repo, this is the Forge one. I'm not maintaining the Fabric version so go here instead: https://github.com/Up-Mods/Glassential
