### ISSUE TITLE
Dark ethereal glass is invisible

### ISSUE THREAD

**Issue by Nubidubi23** [Lykrast/Glassential#8]
The icon is invisible in the hotbar and so is the dropped item , it only gets temporarily fixed when you place 1 down

Glassential 1.16.5 1.1.6

Forge 36.1.16

**Comment by Nubidubi23** [comment]
Update : turns out literally every item is in invisible , in JEI too

**Comment by Lykrast** [comment]
Not having this issue on a fresh Forge 36.1.18 instance, so:

* What other mods do you have installed?
* Does updating forge happen to fix it? (you never know, might be worth a try)

**Comment by Nubidubi23** [comment]
Sorry for not answering for 1000 years , it was an optifine bug , not your fault.
