### ISSUE TITLE
In the servers with Mohist and Arclight as the core, mod is not loaded or invalid.

### ISSUE THREAD

**Issue by SHDocter** [Lykrast/Glassential#9]
In the servers with Mohist and Arclight as the core, mod is not loaded or invalid.

**Comment by Lykrast** [comment]
Well I don't know anything about those, so not sure I can do anything without more details. Like error messages? Log messages? Do these things say anything about what is invalid?

**Comment by SHDocter** [comment]
[main/WARN] [net.minecraftforge.fml.server.ServerModLoader/LOADING]: File glassential-forge-1.16.5-1.1.6.jar is not a jar file

**Comment by SHDocter** [comment]
I don't know if it's a problem with Mohist and Arclight, because there is another mod that will also have this error

**Comment by Lykrast** [comment]
Well not sure I can do anything here, since it's likely on Mohist/Arclight's side. Unless normal forge has any issue with it then I don't think I can do much.
